FROM python:3.9



# Copy the DAG files from the host machine to the image
COPY . /opt/airflow/dags/

# Install any necessary dependencies
# For example, if your DAGs require additional Python packages,
# you can uncomment the following line and provide the requirements.txt file
# COPY requirements.txt /app/requirements.txt
# RUN pip install -r requirements.txt

# # Set the entrypoint to run Airflow
# ENTRYPOINT ["airflow"]

